/*
 * Developed by Akbar Ahmadi Saray
 * Clean Architecture Domain - Base Aggregate Root
 * Base aggregate root class implementing all tracking features
 * Year: 2025
 */

using AkbarAmd.SharedKernel.Domain.Contracts;
using AkbarAmd.SharedKernel.Domain.Contracts.Audits;

namespace AkbarAmd.SharedKernel.Domain.AggregateRoots
{
    /// <summary>
    /// Base aggregate root class with domain events and concurrency control
    /// </summary>
    /// <typeparam name="TKey">The type of the entity identifier</typeparam>
    public abstract class AggregateRoot<TKey> : Entity<TKey>, IAggregateRoot<TKey>, IConcurrentAudit
        where TKey : IEquatable<TKey>
    {
        private readonly List<IDomainEvent> _domainEvents = new();

        /// <summary>
        /// Indicates whether the aggregate root has pending domain events
        /// </summary>
        public bool HasPendingEvents => _domainEvents.Count > 0;

        /// <summary>
        /// Read-only collection of domain events generated by this aggregate root
        /// </summary>
        public IReadOnlyCollection<IDomainEvent> DomainEvents => _domainEvents.AsReadOnly();

        /// <summary>
        /// Row version for optimistic concurrency control (required)
        /// </summary>
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();

        /// <summary>
        /// Default constructor for ORM/ODM support.
        /// Should only be used by infrastructure components.
        /// </summary>
        protected AggregateRoot()
        {
        }

        /// <summary>
        /// Constructor for setting up entity with ID.
        /// </summary>
        /// <param name="id">The entity's unique identifier</param>
        protected AggregateRoot(TKey id) : base(id)
        {
        }

        /// <summary>
        /// Adds a domain event to be published
        /// </summary>
        /// <param name="domainEvent">The domain event to add</param>
        /// <exception cref="ArgumentNullException">Thrown when domainEvent is null</exception>
        protected void AddDomainEvent(IDomainEvent domainEvent)
        {
            _domainEvents.Add(domainEvent ?? throw new ArgumentNullException(nameof(domainEvent)));
        }

        /// <summary>
        /// Clears all domain events from this aggregate
        /// </summary>
        public void ClearDomainEvents()
        {
            _domainEvents.Clear();
        }
    }
}