/*
 * Developed by Akbar Ahmadi Saray
 * Clean Architecture Domain Shared Kernel - Contracts
 * Interface hierarchy for Aggregate Roots with specific responsibilities.
 * Year: 2025
 */

using System.Collections.Generic;

namespace MCA.SharedKernel.Domain.Contracts
{
    /// <summary>
    /// Base contract for all aggregate roots without generic constraints.
    /// Provides core aggregate functionality for domain event management.
    /// </summary>
    public interface IAggregateRoot : IEntity
    {
        /// <summary>
        /// Indicates whether the aggregate root has pending domain events.
        /// </summary>
        bool HasPendingEvents { get; }

        /// <summary>
        /// Read-only collection of domain events generated by this aggregate root.
        /// </summary>
        IReadOnlyCollection<IDomainEvent> DomainEvents { get; }

        /// <summary>
        /// Clears all domain events from this aggregate.
        /// </summary>
        void ClearDomainEvents();
    }

    /// <summary>
    /// Contract for aggregate roots with a strongly-typed identity.
    /// Extends base aggregate functionality with identity management.
    /// </summary>
    /// <typeparam name="TId">Identifier type implementing IEquatable.</typeparam>
    public interface IAggregateRoot<TId> : IAggregateRoot, IEntity<TId>
        where TId : IEquatable<TId>
    {
        /// <summary>
        /// Version for optimistic concurrency control.
        /// </summary>
        long Version { get; }

        /// <summary>
        /// Increment version after successful commit.
        /// </summary>
        void IncrementVersion();
    }
}
